//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.StatisticalService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatisticalService.StatisticalServiceSoap")]
    public interface StatisticalServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object CountTable(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountTable", ReplyAction="*")]
        System.Threading.Tasks.Task<object> CountTableAsync(string table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CategoryStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CategoryStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CategoryStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> CategoryStatisticalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AuthorStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthorStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AuthorStatisticalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PublishStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PublishStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PublishStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> PublishStatisticalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable BookStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BookStatisticalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupplierStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SupplierStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SupplierStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SupplierStatisticalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable OrderStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> OrderStatisticalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable UserStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> UserStatisticalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SliderStatistical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SliderStatistical();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SliderStatistical", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SliderStatisticalAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatisticalServiceSoapChannel : WebForm.StatisticalService.StatisticalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticalServiceSoapClient : System.ServiceModel.ClientBase<WebForm.StatisticalService.StatisticalServiceSoap>, WebForm.StatisticalService.StatisticalServiceSoap {
        
        public StatisticalServiceSoapClient() {
        }
        
        public StatisticalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object CountTable(string table) {
            return base.Channel.CountTable(table);
        }
        
        public System.Threading.Tasks.Task<object> CountTableAsync(string table) {
            return base.Channel.CountTableAsync(table);
        }
        
        public System.Data.DataTable CategoryStatistical() {
            return base.Channel.CategoryStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> CategoryStatisticalAsync() {
            return base.Channel.CategoryStatisticalAsync();
        }
        
        public System.Data.DataTable AuthorStatistical() {
            return base.Channel.AuthorStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AuthorStatisticalAsync() {
            return base.Channel.AuthorStatisticalAsync();
        }
        
        public System.Data.DataTable PublishStatistical() {
            return base.Channel.PublishStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PublishStatisticalAsync() {
            return base.Channel.PublishStatisticalAsync();
        }
        
        public System.Data.DataTable BookStatistical() {
            return base.Channel.BookStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BookStatisticalAsync() {
            return base.Channel.BookStatisticalAsync();
        }
        
        public System.Data.DataTable SupplierStatistical() {
            return base.Channel.SupplierStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SupplierStatisticalAsync() {
            return base.Channel.SupplierStatisticalAsync();
        }
        
        public System.Data.DataTable OrderStatistical() {
            return base.Channel.OrderStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> OrderStatisticalAsync() {
            return base.Channel.OrderStatisticalAsync();
        }
        
        public System.Data.DataTable UserStatistical() {
            return base.Channel.UserStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> UserStatisticalAsync() {
            return base.Channel.UserStatisticalAsync();
        }
        
        public System.Data.DataTable SliderStatistical() {
            return base.Channel.SliderStatistical();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SliderStatisticalAsync() {
            return base.Channel.SliderStatisticalAsync();
        }
    }
}
