//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.PaginationService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaginationService.PaginationServiceSoap")]
    public interface PaginationServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Process", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Process(string tableName, int currentPage, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Process", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ProcessAsync(string tableName, int currentPage, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaginationServiceSoapChannel : WebForm.PaginationService.PaginationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaginationServiceSoapClient : System.ServiceModel.ClientBase<WebForm.PaginationService.PaginationServiceSoap>, WebForm.PaginationService.PaginationServiceSoap {
        
        public PaginationServiceSoapClient() {
        }
        
        public PaginationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaginationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaginationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaginationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Process(string tableName, int currentPage, int pageSize) {
            return base.Channel.Process(tableName, currentPage, pageSize);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ProcessAsync(string tableName, int currentPage, int pageSize) {
            return base.Channel.ProcessAsync(tableName, currentPage, pageSize);
        }
    }
}
