//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.OrderService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.OrderServiceSoap")]
    public interface OrderServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCartByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCartByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCartByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetCartByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Search(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SearchAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddCart(string isbn, string username, string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCart", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddCartAsync(string isbn, string username, string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EditCart(string isbn, string username, string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCart", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EditCartAsync(string isbn, string username, string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCart", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteCart(string isbn, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCart", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCartAsync(string isbn, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderByUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOrderByUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrderID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateOrderID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrderID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateOrderIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CreateOrder(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateOrderAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool PaymentOrder(string username, string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> PaymentOrderAsync(string username, string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object TotalOrder(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TotalOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<object> TotalOrderAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object CountOrder(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<object> CountOrderAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderBill(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderBill", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOrderBillAsync(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetailBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderDetailBill(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetailBill", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOrderDetailBillAsync(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetailsByOrderID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderDetailsByOrderID(string orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetailsByOrderID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetOrderDetailsByOrderIDAsync(string orderID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceSoapChannel : WebForm.OrderService.OrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceSoapClient : System.ServiceModel.ClientBase<WebForm.OrderService.OrderServiceSoap>, WebForm.OrderService.OrderServiceSoap {
        
        public OrderServiceSoapClient() {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetCartByUsername(string username) {
            return base.Channel.GetCartByUsername(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetCartByUsernameAsync(string username) {
            return base.Channel.GetCartByUsernameAsync(username);
        }
        
        public System.Data.DataTable Search(string keyword) {
            return base.Channel.Search(keyword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SearchAsync(string keyword) {
            return base.Channel.SearchAsync(keyword);
        }
        
        public bool AddCart(string isbn, string username, string amount) {
            return base.Channel.AddCart(isbn, username, amount);
        }
        
        public System.Threading.Tasks.Task<bool> AddCartAsync(string isbn, string username, string amount) {
            return base.Channel.AddCartAsync(isbn, username, amount);
        }
        
        public bool EditCart(string isbn, string username, string amount) {
            return base.Channel.EditCart(isbn, username, amount);
        }
        
        public System.Threading.Tasks.Task<bool> EditCartAsync(string isbn, string username, string amount) {
            return base.Channel.EditCartAsync(isbn, username, amount);
        }
        
        public bool DeleteCart(string isbn, string username) {
            return base.Channel.DeleteCart(isbn, username);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCartAsync(string isbn, string username) {
            return base.Channel.DeleteCartAsync(isbn, username);
        }
        
        public System.Data.DataTable GetOrder() {
            return base.Channel.GetOrder();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOrderAsync() {
            return base.Channel.GetOrderAsync();
        }
        
        public System.Data.DataTable GetOrderByUsername(string username) {
            return base.Channel.GetOrderByUsername(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOrderByUsernameAsync(string username) {
            return base.Channel.GetOrderByUsernameAsync(username);
        }
        
        public string CreateOrderID() {
            return base.Channel.CreateOrderID();
        }
        
        public System.Threading.Tasks.Task<string> CreateOrderIDAsync() {
            return base.Channel.CreateOrderIDAsync();
        }
        
        public bool CreateOrder(string username) {
            return base.Channel.CreateOrder(username);
        }
        
        public System.Threading.Tasks.Task<bool> CreateOrderAsync(string username) {
            return base.Channel.CreateOrderAsync(username);
        }
        
        public bool PaymentOrder(string username, string orderID) {
            return base.Channel.PaymentOrder(username, orderID);
        }
        
        public System.Threading.Tasks.Task<bool> PaymentOrderAsync(string username, string orderID) {
            return base.Channel.PaymentOrderAsync(username, orderID);
        }
        
        public object TotalOrder(string username) {
            return base.Channel.TotalOrder(username);
        }
        
        public System.Threading.Tasks.Task<object> TotalOrderAsync(string username) {
            return base.Channel.TotalOrderAsync(username);
        }
        
        public object CountOrder(string username) {
            return base.Channel.CountOrder(username);
        }
        
        public System.Threading.Tasks.Task<object> CountOrderAsync(string username) {
            return base.Channel.CountOrderAsync(username);
        }
        
        public System.Data.DataTable GetOrderBill(string orderID) {
            return base.Channel.GetOrderBill(orderID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOrderBillAsync(string orderID) {
            return base.Channel.GetOrderBillAsync(orderID);
        }
        
        public System.Data.DataTable GetOrderDetailBill(string orderID) {
            return base.Channel.GetOrderDetailBill(orderID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOrderDetailBillAsync(string orderID) {
            return base.Channel.GetOrderDetailBillAsync(orderID);
        }
        
        public System.Data.DataTable GetOrderDetailsByOrderID(string orderID) {
            return base.Channel.GetOrderDetailsByOrderID(orderID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetOrderDetailsByOrderIDAsync(string orderID) {
            return base.Channel.GetOrderDetailsByOrderIDAsync(orderID);
        }
    }
}
