//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.PublishService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublishService.PublishServiceSoap")]
    public interface PublishServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItemById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemById", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetItemByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableWithPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTableWithPage(string startIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableWithPage", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTableWithPageAsync(string startIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Search(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SearchAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Add(string publishName, string phone, string address, string fax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddAsync(string publishName, string phone, string address, string fax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Edit(string publishID, string publishName, string phone, string address, string fax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EditAsync(string publishID, string publishName, string phone, string address, string fax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Delete(string publishID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string publishID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PublishServiceSoapChannel : WebForm.PublishService.PublishServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublishServiceSoapClient : System.ServiceModel.ClientBase<WebForm.PublishService.PublishServiceSoap>, WebForm.PublishService.PublishServiceSoap {
        
        public PublishServiceSoapClient() {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetItemById(string id) {
            return base.Channel.GetItemById(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetItemByIdAsync(string id) {
            return base.Channel.GetItemByIdAsync(id);
        }
        
        public System.Data.DataTable GetTable() {
            return base.Channel.GetTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTableAsync() {
            return base.Channel.GetTableAsync();
        }
        
        public System.Data.DataTable GetTableWithPage(string startIndex) {
            return base.Channel.GetTableWithPage(startIndex);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTableWithPageAsync(string startIndex) {
            return base.Channel.GetTableWithPageAsync(startIndex);
        }
        
        public System.Data.DataTable Search(string keyword) {
            return base.Channel.Search(keyword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SearchAsync(string keyword) {
            return base.Channel.SearchAsync(keyword);
        }
        
        public bool Add(string publishName, string phone, string address, string fax) {
            return base.Channel.Add(publishName, phone, address, fax);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(string publishName, string phone, string address, string fax) {
            return base.Channel.AddAsync(publishName, phone, address, fax);
        }
        
        public bool Edit(string publishID, string publishName, string phone, string address, string fax) {
            return base.Channel.Edit(publishID, publishName, phone, address, fax);
        }
        
        public System.Threading.Tasks.Task<bool> EditAsync(string publishID, string publishName, string phone, string address, string fax) {
            return base.Channel.EditAsync(publishID, publishName, phone, address, fax);
        }
        
        public bool Delete(string publishID) {
            return base.Channel.Delete(publishID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string publishID) {
            return base.Channel.DeleteAsync(publishID);
        }
    }
}
