//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm.UserService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SignUp(string username, string password, string fullname, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignUp", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SignUpAsync(string username, string password, string fullname, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Edit(string username, string status, string accountTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Edit", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EditAsync(string username, string status, string accountTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Delete(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItemById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemById", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetItemByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableWithPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTableWithPage(string startIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableWithPage", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetTableWithPageAsync(string startIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Search(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SearchAsync(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountTypeTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAccountTypeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountTypeTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAccountTypeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object GetMoney(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<object> GetMoneyAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateMoney(string username, string coin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateMoneyAsync(string username, string coin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : WebForm.UserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<WebForm.UserService.UserServiceSoap>, WebForm.UserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool SignUp(string username, string password, string fullname, string email) {
            return base.Channel.SignUp(username, password, fullname, email);
        }
        
        public System.Threading.Tasks.Task<bool> SignUpAsync(string username, string password, string fullname, string email) {
            return base.Channel.SignUpAsync(username, password, fullname, email);
        }
        
        public bool Edit(string username, string status, string accountTypeID) {
            return base.Channel.Edit(username, status, accountTypeID);
        }
        
        public System.Threading.Tasks.Task<bool> EditAsync(string username, string status, string accountTypeID) {
            return base.Channel.EditAsync(username, status, accountTypeID);
        }
        
        public bool Delete(string username) {
            return base.Channel.Delete(username);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string username) {
            return base.Channel.DeleteAsync(username);
        }
        
        public System.Data.DataTable GetItemById(string id) {
            return base.Channel.GetItemById(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetItemByIdAsync(string id) {
            return base.Channel.GetItemByIdAsync(id);
        }
        
        public System.Data.DataTable GetTable() {
            return base.Channel.GetTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTableAsync() {
            return base.Channel.GetTableAsync();
        }
        
        public System.Data.DataTable GetTableWithPage(string startIndex) {
            return base.Channel.GetTableWithPage(startIndex);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetTableWithPageAsync(string startIndex) {
            return base.Channel.GetTableWithPageAsync(startIndex);
        }
        
        public System.Data.DataTable Search(string keyword) {
            return base.Channel.Search(keyword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SearchAsync(string keyword) {
            return base.Channel.SearchAsync(keyword);
        }
        
        public System.Data.DataTable GetAccountTypeTable() {
            return base.Channel.GetAccountTypeTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAccountTypeTableAsync() {
            return base.Channel.GetAccountTypeTableAsync();
        }
        
        public object GetMoney(string username) {
            return base.Channel.GetMoney(username);
        }
        
        public System.Threading.Tasks.Task<object> GetMoneyAsync(string username) {
            return base.Channel.GetMoneyAsync(username);
        }
        
        public bool UpdateMoney(string username, string coin) {
            return base.Channel.UpdateMoney(username, coin);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMoneyAsync(string username, string coin) {
            return base.Channel.UpdateMoneyAsync(username, coin);
        }
    }
}
